# Generated by Django 3.2.7 on 2022-04-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_auto_20220418_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
    ]
